#!/bin/sh
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

payload=$TMPDIR/git-resource-request

cat > $payload <&0

load_pubkey $payload
configure_git_ssl_verification $payload
configure_credentials $payload

uri=$(jq -r '.source.uri // ""' < $payload)
git_config_payload=$(jq -r '.source.git_config // []' < $payload)

previous_branches="$(jq -r '.version.branches // ""' < $payload)"

configure_git_global "${git_config_payload}"

current_branches="$(git ls-remote -h "$uri" | awk '{print $NF}' | sed 's/refs\/heads\///' | sort)"

set_sub() {
  jq -nr '($a | split("\n")) - ($b | split("\n")) | join("\n")' \
    --arg a "$1" \
    --arg b "$2"
}

echo "previous: $previous_branches"
echo "current:  $current_branches"

if [ "$current_branches" = "$previous_branches" ]; then
  echo '[]' >&3
else
  removed="$(set_sub "$previous_branches" "$current_branches")"
  added="$(set_sub "$current_branches" "$previous_branches")"

  jq -n '[
    {
      removed: $removed,
      added: $added,
      branches: $branches
    }
  ]' \
    --arg removed "$removed" \
    --arg added "$added" \
    --arg branches "$current_branches" \
    >&3
fi
