#!/bin/sh
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

destination=$1

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

payload=$(mktemp $TMPDIR/git-resource-request.XXXXXX)

cat > $payload <&0

cd $destination

jq -r '.version.branches // ""' < $payload > branches
jq -r '.version.added // ""' < $payload > added
jq -r '.version.removed // ""' < $payload > removed

jq '{version}' < $payload >&3
